### ISSUE TITLE
Error: Cannot Read Geometry From KML. Cannot construct Point. z should be numeric

### ISSUE THREAD

**Issue by wisze** [mprins/dokuwiki-plugin-spatialhelper#35]
## environment

  - php version: 
  - dokuwiki version: 2022-07-31a "Igor"
  - plugin version / date:  11-11-2022
  - list of any other plugins (apart from bundled plugins): geophp, geotag, etc.
  
## expected behaviour

Display openlayers map on [my webpage](https://wiki.wisze.org/) with icons from a [KML file](https://wiki.wisze.org/lib/exe/fetch.php/en/sitemap.kml). This worked fine with the previous version of openlayersmap.

## actual behaviour

Error message (see log).

### error log
2022-11-13 11:42:00	/home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/geophp/vendor/funiq/geophp/src/Adapter/KML.php(74)	Exception: Cannot Read Geometry From KML. Cannot construct Point. z should be numeric
  #0 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/geophp/vendor/funiq/geophp/src/Adapter/KML.php(53): geoPHP\Adapter\KML->geomFromText()
  mprins/dokuwiki-plugin-openlayersmap#1 [internal function]: geoPHP\Adapter\KML->read()
  mprins/dokuwiki-plugin-openlayersmap#2 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/geophp/vendor/funiq/geophp/src/geoPHP.php(126): call_user_func_array()
  mprins/dokuwiki-plugin-openlayersmap#3 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/StaticMap.php(275): geoPHP\geoPHP::load()
  mprins/dokuwiki-plugin-openlayersmap#4 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/StaticMap.php(241): dokuwiki\plugin\openlayersmap\StaticMap->autoZoom()
  mprins/dokuwiki-plugin-openlayersmap#5 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/helper/staticmap.php(129): dokuwiki\plugin\openlayersmap\StaticMap->getMap()
  mprins/dokuwiki-plugin-openlayersmap#6 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/syntax/olmap.php(549): helper_plugin_openlayersmap_staticmap->getMap()
  mprins/dokuwiki-plugin-openlayersmap#7 /home/w102582/domains/wisze.org/public_html/wiki/lib/plugins/openlayersmap/syntax/olmap.php(149): syntax_plugin_openlayersmap_olmap->getStaticOSM()
  mprins/dokuwiki-plugin-openlayersmap#8 /home/w102582/domains/wisze.org/public_html/wiki/inc/parser/handler.php(279): syntax_plugin_openlayersmap_olmap->handle()
  mprins/dokuwiki-plugin-openlayersmap#9 /home/w102582/domains/wisze.org/public_html/wiki/inc/Parsing/Lexer/Lexer.php(270): Doku_Handler->plugin()
  mprins/dokuwiki-plugin-openlayersmap#10 /home/w102582/domains/wisze.org/public_html/wiki/inc/Parsing/Lexer/Lexer.php(197): dokuwiki\Parsing\Lexer\Lexer->invokeHandler()
  mprins/dokuwiki-plugin-openlayersmap#11 /home/w102582/domains/wisze.org/public_html/wiki/inc/Parsing/Lexer/Lexer.php(147): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens()
  mprins/dokuwiki-plugin-openlayersmap#12 /home/w102582/domains/wisze.org/public_html/wiki/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse()
  mprins/dokuwiki-plugin-openlayersmap#13 /home/w102582/domains/wisze.org/public_html/wiki/inc/parserutils.php(223): dokuwiki\Parsing\Parser->parse()
  mprins/dokuwiki-plugin-openlayersmap#14 /home/w102582/domains/wisze.org/public_html/wiki/inc/parserutils.php(188): p_get_instructions()
  mprins/dokuwiki-plugin-openlayersmap#15 /home/w102582/domains/wisze.org/public_html/wiki/inc/parserutils.php(510): p_cached_instructions()
  mprins/dokuwiki-plugin-openlayersmap#16 /home/w102582/domains/wisze.org/public_html/wiki/inc/parserutils.php(289): p_render_metadata()
  mprins/dokuwiki-plugin-openlayersmap#17 /home/w102582/domains/wisze.org/public_html/wiki/inc/common.php(246): p_get_metadata()
  mprins/dokuwiki-plugin-openlayersmap#18 /home/w102582/domains/wisze.org/public_html/wiki/doku.php(97): pageinfo()
  mprins/dokuwiki-plugin-openlayersmap#19 {main}

**Comment by mprins** [comment]
probably cause by https://github.com/mprins/dokuwiki-plugin-spatialhelper/pull/32

**Comment by wisze** [comment]
The KML is indeed generated by spatialhelper. The question is whether this is a bug in spatialhelper. The z value should not be necessary. According to the [KML tutorial](https://developers.google.com/kml/documentation/kml_tut#placemarks) the altitude is optional for specifying a point. The KML is generated from {{geotag}}s on the dokuwiki pages. And for {{geotag}} the altitude is optional too.

**Comment by mprins** [comment]
it sems to be a bug in PHP where `isset($meta['geo']['alt']` return an empty string instead of a boolean:
https://onlinephp.io?s=s7EvyCjg5eLlUslNLUmMVk9PzVePjVbPSSxRj1WwVQAxMksyS1NS1a1BqgqKMvNKNECiVgq66noKmcXFqSUaWPRqKijoKenG5ClpIusDK1dIzMGjGygJ0o1Fc2puQUklTLOCngKYj103XDsA&v=8.1.12

**Comment by mprins** [comment]
updating this and the geotag plugin and erasing the spatial index from the admin page (`doku.php?id=start&do=admin&page=spatialhelper_purge`) should fix the data

**Comment by wisze** [comment]
Solved, works as expected after update of spatialhelper, geotag en openlayers
