### ISSUE TITLE
Spatial helper not writing KML file

### ISSUE THREAD

**Issue by 8BitSensei** [mprins/dokuwiki-plugin-spatialhelper#43]
## Spatialhelper throwing an undefined array key error whenever a new page is created or updated
I'm attempting to use the spatialhelper in a Dokuwiki running from a container along with the geotag and openalyers map plugin, I have the geophp plugin installed and I've updated my `mime.local.conf` as described in the docs.

Every time I add or update a page, whether it is geotagged or not, I seen an undefined array key error reported in the error logs by the spatialhelper plugin.  No KML or GEORSS file is then created, or updated in the media directory.

### To Reproduce
Steps to reproduce the behaviour:
1. Running Dokuwiki
2. Install the plugins GeoPHP, Geotag, Openlayers map, and spatialhelper plugin
4. Create a new page e.g. `:new_location` and add a geotag
5. On another page e.g. `:map` insert the openlayers map with the `kml` parameter set to `:sitemap.kml`
6. Note that the map does not display geotagged pages, adding more geotagged pages or updating pages does not make a difference

## Expected behaviour
When a new page is added to the Dokuwiki site with a geotag from the Geotag plugin, the KML and GEORSS files in the media manager should be updated with it's location, or created if it does not already exist/

## environment

  - php version: 8.2.10, 8.2.8, 8.1.23, and 7.4.33
  - dokuwiki version: 2023-04-04a "Jack Jackrum"
  - plugin version / date: 2023-06-30
  - list of any other plugins (apart from bundled plugins): GeoPHP 2023-07-14, GeoTag 2023-07-14, OpenLayersMap 2023-09-09

### error log
```
2023-09-11 11:47:04
E_WARNING: Undefined array key 0
/config/dokuwiki/lib/plugins/spatialhelper/helper/index.php(136)
#0 /config/dokuwiki/lib/plugins/spatialhelper/helper/index.php(136): dokuwiki\ErrorHandler::errorHandler()
#1 /config/dokuwiki/lib/plugins/spatialhelper/helper/index.php(109): helper_plugin_spatialhelper_index->addToIndex()
#2 /config/dokuwiki/lib/plugins/spatialhelper/action.php(87): helper_plugin_spatialhelper_index->updateSpatialIndex()
#3 /app/www/public/inc/Extension/EventHandler.php(80): action_plugin_spatialhelper->handleIndexerPageAdd()
#4 /app/www/public/inc/Extension/Event.php(74): dokuwiki\Extension\EventHandler->process_event()
#5 /app/www/public/inc/indexer.php(184): dokuwiki\Extension\Event->advise_before()
#6 /app/www/public/inc/TaskRunner.php(199): idx_addPage()
#7 /app/www/public/inc/TaskRunner.php(50): dokuwiki\TaskRunner->runIndexer()
#8 /app/www/public/lib/exe/taskrunner.php(16): dokuwiki\TaskRunner->run()
```

### debug log
No log entries are being produced, `allowdebug` is turned on in the configuration manager

**Comment by mprins** [comment]
I don't see any error in you log snippet.
Is the spatial index file created? In `$conf['indexdir']/spatial.idx`

Sitemap files are generated when the http://www.dokuwiki.org/devel:event:sitemap_generate event is fired this can take some time

**Comment by 8BitSensei** [comment]
Yep, so I can see `spatial.idx` under `data/index/`, and I can see that it is created as soon as I add a new page with a geotag:
`a:1:{s:9:"u1m35jh8h";a:1:{i:0;s:3:"new";}}`

**Comment by mprins** [comment]
the index entry looks OK; have you configured a value greater than 0 for the sitemap config, see https://www.dokuwiki.org/config:sitemap

**Comment by 8BitSensei** [comment]
I hadn't, I guess at a minimum I'll have to wait a day to test this, but it seems like this is the issue considering everything else is working fine.
