### ISSUE TITLE
Add title or link to spatial index

### ISSUE THREAD

**Issue by e-dschungel** [mprins/dokuwiki-plugin-spatialhelper#49]
Hi,

is there a way to add a title or a link to the spatial index items so the index items can be nicely presented on a openlayersmap?

Background:
I'd like to  create pages for different POIs, geotag them with the geotag plugin, create a spatial index with this plugins and show the items on a openlayersmap. From there I'd like to have links to POI pages. For that usecase #18 would be usful as well.

**Comment by mprins** [comment]
the spatial index is only that an index of geohash related page-ids (1:n) and is meant for searching, adding anything other to the index defeats the purpose of geohash based spatial.

the plugin generates both GeoRRS and KML (namespaced) sitemaps while indexing, these can be loaded in openlayersmap using eg. `kmlfile=:sitemap.kml` see https://dokuwikispatial.sourceforge.io/dokuwiki/doku.php/spatialhelper/start for syntax or https://wild-water.nl/dokuwiki/beschrijvingen/belgie/start#kaart for a working example
the KML file has relevant info from the page.

**Comment by e-dschungel** [comment]
Ah, got it now.

It there a way to avoid adding the geo metadata to a page with an openlayersmap with coordinates different from the default values lat="50.0" lon="5.1"? Otherwise the KML Sitemap has an entry of this map page and with the default values my POIs from the KML (located in northern germany) are a bit off.

**Comment by mprins** [comment]
change the initial values for the map
