### ISSUE TITLE
spatial sitemap per namespace

### ISSUE THREAD

**Issue by mprins** [mprins/dokuwiki-plugin-spatialhelper#7]
Add an option to generate a spatial sitemap per namespace

**Comment by edwinwisse** [comment]
The sitemaps for namespaces are not updated together with the top sitemap. I have added two namespaces ('nl' and 'en') and have a number of pages in both namespaces with geotags. The sitemap per namespace is not generated at the same time as the top sitemap. 
I have reset the spatial index in the admin pages. (I get a series of error messages, all about the exif headers.) After resetting the spatial index there are new files sitemap.georss and sitemap.kml. But no new sitemap files in the 'en' and 'nl' namespaces.

**Comment by mprins** [comment]
All spatial sitemaps are (re-)generated after the SITEMAP_GENERATE fires as you can see here: https://github.com/mprins/dokuwiki-plugin-spatialhelper/blob/master/action.php#L51 and here: https://github.com/mprins/dokuwiki-plugin-spatialhelper/blob/master/action.php#L145 

As you can see in the code all sitemaps are generated one after another. The content of the spatial sitemap is based on the spatial index which gets updated when a page is added to the index (after the INDEXER_PAGE_ADD event) or when an image is uploaded (before MEDIA_UPLOAD_FINISH event).

Note that you will need to specify the fully qualified namespace eg. for http://wild-water.nl/dokuwiki/beschrijvingen/duitsland/start I have the following configured:
```
beschrijvingen
beschrijvingen:duitsland
```
this will generate kml/georss in both `beschrijvingen:duitsland` (containing only pages in and below that namespace) and `beschrijvingen` (containing pages in that namespace and recursively all subnamespaces including `beschrijvingen:duitsland`)

**Comment by edwinwisse** [comment]
So the sitemaps under namespaces are generated after a page is added or image is uploaded only?
The root sitemap.kml and sitemap.georss are generated when the admin resets the spatial index. 
One more (probably stupid) question: does _changing_ a page (adding a geotag for example) also result in an INDEXER_PAGE_ADD event? I have added and modified pages but i see now new sitemaps in the language namespaces.

For the record: my site [http://wiki.wisze.net/](http://wiki.wisze.net/) has a number of namespaces for different languages. I have the following namespaces in `plugin»spatialhelper»sitemap_namespaces` 
`en
nl
nl:kaarten`
and for `plugin»spatialhelper»media_kml` have tried both `:sitemap.kml` and `sitemap.kml`.

**Comment by edwinwisse** [comment]
I think i got something: if there is a `sitemap.xml.gz` file in the cache the sitemaps per namespace are not generated. For some reason the root sitemap _is_ generated even though the file is in the cache.
After removing the file from the cache and resetting the spatial index all sitemap files are freshly made :-)
